// This file is autogenerated by tools/update-file-sizes.js
VIZ.fileSizes = {
  "data/average-actual-delays.json": 8084,
  "data/delay.json": 2823001,
  "data/marey-header.json": 1381,
  "data/marey-trips.json": 818145,
  "data/spider.json": 1928,
  "data/station-network.json": 5389,
  "data/station-paths.json": 927,
};
VIZ.fileHashes = {
  "data/average-actual-delays.json": "f71ded52",
  "data/delay.json": "8a7da593",
  "data/marey-header.json": "b6bafbc1",
  "data/marey-trips.json": "27ee0dfe",
  "data/spider.json": "8b678242",
  "data/station-network.json": "9511bc5d",
  "data/station-paths.json": "4bc82be2",
};